@HomeBoxNet.API_HostAddress = http://localhost:5160

POST {{HomeBoxNet.API_HostAddress}}/v1/users/login/
Accept: application/json
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###
